/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found. It
 * should not be modified by hand.
 */

package com.google.android.material;

public final class Manifest {
  public static final class permission {
    public static final String DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION="com.google.android.material.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION";
  }

}